# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import serial



class Ui_MainWindow(object):

    def __init__(self):
        self.tmr_var = 0
        self.Baudarate = 115200
        self.Bytesize = serial.EIGHTBITS
        self.Stopbits = serial.STOPBITS_ONE
        self.ser = serial.Serial(
            port='COM3',
            baudrate=self.Baudarate,
            parity=serial.PARITY_NONE,
            stopbits=self.Stopbits,
            bytesize=self.Bytesize,
            timeout=0.1
        )

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(509, 260)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.baudBox = QtWidgets.QComboBox(self.centralwidget)
        self.baudBox.setGeometry(QtCore.QRect(40, 220, 69, 22))
        self.baudBox.setObjectName("baudBox")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.baudBox.addItem("")
        self.dataBox = QtWidgets.QComboBox(self.centralwidget)
        self.dataBox.setGeometry(QtCore.QRect(130, 220, 69, 22))
        self.dataBox.setObjectName("dataBox")
        self.dataBox.addItem("")
        self.dataBox.addItem("")
        self.dataBox.addItem("")
        self.dataBox.addItem("")
        self.parityBox = QtWidgets.QComboBox(self.centralwidget)
        self.parityBox.setGeometry(QtCore.QRect(220, 220, 69, 22))
        self.parityBox.setObjectName("parityBox")
        self.parityBox.addItem("")
        self.parityBox.addItem("")
        self.parityBox.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 200, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 200, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 200, 47, 13))
        self.label_3.setObjectName("label_3")

        self.lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd.setGeometry(QtCore.QRect(60, 40, 131, 61))
        self.lcd.setObjectName("lcd")

        self.lcd1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd1.setGeometry(QtCore.QRect(60, 120, 131, 61))
        self.lcd1.setObjectName("lcd1")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 20, 111, 16))
        self.label_4.setObjectName("label_4")

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 105, 111, 16))
        self.label_6.setObjectName("label_6")

        self.temp_input = QtWidgets.QLineEdit(self.centralwidget)
        self.temp_input.setGeometry(QtCore.QRect(330, 50, 113, 20))
        self.temp_input.setObjectName("temp_input")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 30, 101, 16))
        self.label_5.setObjectName("label_5")
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setGeometry(QtCore.QRect(350, 80, 75, 23))
        self.button.setObjectName("button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 509, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.baudBox.setCurrentIndex(11)
        self.dataBox.setCurrentIndex(3)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.baudBox.setItemText(0, _translate("MainWindow", "600"))
        self.baudBox.setItemText(1, _translate("MainWindow", "1200"))
        self.baudBox.setItemText(2, _translate("MainWindow", "2400"))
        self.baudBox.setItemText(3, _translate("MainWindow", "4800"))
        self.baudBox.setItemText(4, _translate("MainWindow", "9600"))
        self.baudBox.setItemText(5, _translate("MainWindow", "14400"))
        self.baudBox.setItemText(6, _translate("MainWindow", "19200"))
        self.baudBox.setItemText(7, _translate("MainWindow", "28800"))
        self.baudBox.setItemText(8, _translate("MainWindow", "38400"))
        self.baudBox.setItemText(9, _translate("MainWindow", "56000"))
        self.baudBox.setItemText(10, _translate("MainWindow", "57600"))
        self.baudBox.setItemText(11, _translate("MainWindow", "115200"))
        self.baudBox.setItemText(12, _translate("MainWindow", "128000"))
        self.baudBox.setItemText(13, _translate("MainWindow", "256000"))
        self.dataBox.setItemText(0, _translate("MainWindow", "5"))
        self.dataBox.setItemText(1, _translate("MainWindow", "6"))
        self.dataBox.setItemText(2, _translate("MainWindow", "7"))
        self.dataBox.setItemText(3, _translate("MainWindow", "8"))
        self.parityBox.setItemText(0, _translate("MainWindow", "1"))
        self.parityBox.setItemText(1, _translate("MainWindow", "1.5"))
        self.parityBox.setItemText(2, _translate("MainWindow", "2"))
        self.label.setText(_translate("MainWindow", "Baud rate"))
        self.label_2.setText(_translate("MainWindow", "Data bits"))
        self.label_3.setText(_translate("MainWindow", "Stop bits"))
        self.label_4.setText(_translate("MainWindow", "Aktualna temperatura"))
        self.label_5.setText(_translate("MainWindow", "Zadana temperatura"))
        self.label_6.setText(_translate("MainWindow", "Zadana temperatura"))
        self.button.setText(_translate("MainWindow", "Wyślij"))



        #LCD Wyswietlanie temperatury
        self.lcd1.setDigitCount(2)  #liczba wyswietlanych cyfr
        self.lcd1.display(20)         #wyswietlana cyfra

        self.lcd.setDigitCount(5)

        #timer

        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.updateTemp)
        self.timer.timeout.connect(self.updateSerial)
        self.timer.start(100)



        self.button.clicked.connect(self.click)

    def updateSerial(self):

        x = int(self.baudBox.currentText())         #baud
        y = int(self.dataBox.currentText())        #data
        z = float(self.parityBox.currentText())    #stop

        # baud rate
        self.Baudarate = x

        # data bits
        if y == 5:
            self.Bytesize = serial.FIVEBITS
        if y == 6:
            self.Bytesize = serial.SIXBITS
        if y == 7:
            self.Bytesize = serial.SEVENBITS
        if y == 8:
            self.Bytesize = serial.EIGHTBITS

        # stop bits
        if z == 1.0:
            self.Stopbits = serial.STOPBITS_ONE
        if z == 1.5:
            self.Stopbits = serial.STOPBITS_ONE_POINT_FIVE
        if z == 2.0:
            self.Stopbits = serial.STOPBITS_TWO

    def updateTemp(self):
        self.data = self.ser.readline()
        if self.data:
            self.data = self.data.decode()
            self.lcd.display(float(self.data))


    def click(self): ## wyslanie zadanej temperatury
        temperatura_zadana = int(self.temp_input.text())
        if  temperatura_zadana >= 20 and temperatura_zadana <= 40:
            self.lcd1.display(temperatura_zadana)         #wyswietlana cyfra
            ##### Wysylanie temperatury przez uart
            self.ser.write(temperatura_zadana) # trza zrobic
            self.ser.close()

        else:
            self.show_popup()


    def show_popup(self):
        msg = QMessageBox()
        msg.setWindowTitle("Error")
        msg.setText("Wartość temperatury musi być z zakresu 20-40°C")
        msg.setIcon(QMessageBox.Critical)
        msg.setStandardButtons(QMessageBox.Cancel)
        msg.setDefaultButton(QMessageBox.Cancel)
        x = msg.exec_()


    def show_popup1(self):
        msg = QMessageBox()
        msg.setWindowTitle("Error")
        msg.setText("Nie otrzymano wartosci temperatury")
        msg.setIcon(QMessageBox.Critical)
        msg.setStandardButtons(QMessageBox.Retry)
        msg.setDefaultButton(QMessageBox.Retry)
        x = msg.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
